#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:
  supplychain-sandbox:
    image: digitalasset/supplychain-sandbox:0.1.0
    build:
      context: .
      dockerfile: sandbox.Dockerfile
    ports:
      - "127.0.0.1:6865:6865"
      - "127.0.0.1:7500:7500"
  supplychain-triggers:
    image: digitalasset/supplychain-triggers:0.1.0
    build:
      context: .
      dockerfile: triggers.Dockerfile
    depends_on:
      - "supplychain-sandbox"
    environment:
      - LEDGER_HOST=supplychain-sandbox
      - LEDGER_PORT=6865
