#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:

  supplychain-builder:
    image: digitalasset/supplychain-builder:0.1.0
    build:
      context: .
      dockerfile: builder.Dockerfile
    volumes:
      - artifacts:/home/daml/deploy

  supplychain-sandbox:
    image: digitalasset/supplychain-sandbox:0.1.0
    build:
      context: .
      dockerfile: sandbox.Dockerfile
    ports:
      - "127.0.0.1:6865:6865"
      - "127.0.0.1:7500:7500"
      - "127.0.0.1:7575:7575"

  supplychain-triggers:
    image: digitalasset/supplychain-triggers:0.1.0
    build:
      context: .
      dockerfile: triggers.Dockerfile
    depends_on:
      - "supplychain-builder"
      - "supplychain-sandbox"
    environment:
      - LEDGER_HOST=supplychain-sandbox
      - LEDGER_PORT=6865
    volumes:
      - artifacts:/home/daml/deploy:ro

  supplychain-ui:
    image: digitalasset/supplychain-ui:0.1.0
    build:
      context: .
      dockerfile: ui.Dockerfile
    depends_on:
      - "supplychain-builder"
      - "supplychain-sandbox"
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - REACT_APP_JSON_API_URL=http://supplychain-sandbox:7575

volumes:
  artifacts:
