#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:
  supplychain-sandbox:
    image: digitalasset/supplychain-sandbox:0.1.0
    build:
      context: .
      dockerfile: Dockerfile-sandbox
    ports:
      - "127.0.0.1:6865:6865"
  supplychain-navigator:
    image: digitalasset/supplychain-navigator:0.1.0
    build:
      context: .
      dockerfile: Dockerfile-navigator
    depends_on:
      - "supplychain-sandbox"
    ports:
      - "127.0.0.1:7500:7500"
    environment:
      - SANDBOX_HOST=supplychain-sandbox
      - SANDBOX_PORT=6865
  supplychain-bots:
    image: digitalasset/supplychain-bots:0.1.0
    build:
      context: .
      dockerfile: Dockerfile-bots
    depends_on:
      - "supplychain-sandbox"
    environment:
      - SANDBOX_HOST=supplychain-sandbox
      - SANDBOX_PORT=6865
