#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 2.1

executors:
  daml-executor:
    docker:
      - image: circleci/openjdk:11.0-jdk
  docker_buildpack:
    docker:
      - image: circleci/buildpack-deps:xenial

only-release-tags: &only-release-tags
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

commands:
  install_sdk:
    description: "Install the DAML SDK"
    parameters:
      version:
        type: string
    steps:
      - run:
          command: |
            ./scripts/install-daml.sh << parameters.version >>

jobs:
  mvn_test:
    parameters:
      daml_sdk_version:
        type: string
    executor: daml-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}-{{ checksum "daml.yaml" }}
            - m2
      - install_sdk:
          version: << parameters.daml_sdk_version >>
      - run:
          command: |
            export PATH=${HOME}/.daml/bin:${PATH}
            mvn verify
      - save_cache:
          paths:
            - ~/.m2
            - ~/.daml
          key: m2-{{ checksum "pom.xml" }}-{{ checksum "daml.yaml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports
      - run:
          name: Run Blackduck Detect
          command: |
            bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) ci-build digitalasset_ex-supply-chain master --logging.level.com.synopsys.integration=DEBUG --detect.notices.report=true --detect.report.timeout=480
      - run:
          command: cp digitalasset_ex_supply_chain_master_Black_Duck_Notices_Report.txt target/NOTICE
      - persist_to_workspace:
          root: target
          paths:
            - "*.jar"
            - "*.dar"
            - "lib"
            - "NOTICE"

  daml_test:
    parameters:
      daml_sdk_version:
        type: string
    executor: daml-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - daml-{{ checksum "daml.yaml" }}
      - install_sdk:
          version: << parameters.daml_sdk_version >>
      - run:
          command: |
            export PATH=${HOME}/.daml/bin:${PATH}
            daml build -o target/supplychain.dar
            daml test --junit target/daml-test-reports/daml-test.xml --files src/main/daml/DA/RefApps/SupplyChain/Scenarios.daml
      - save_cache:
          paths:
            - ~/.daml
          key: daml-{{ checksum "daml.yaml" }}
      - store_test_results:
          path: target/daml-test-reports
      - store_artifacts:
          path: target/daml-test-reports

  github_release:
    executor: docker_buildpack
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Push a new github release
          command: |
            ./scripts/release.sh ex-supply-chain

workflows:
  version: 2
  build_and_test:
    jobs:
      - daml_test:
          daml_sdk_version: "0.13.54"
      - mvn_test:
          daml_sdk_version: "0.13.54"
          context: blackduck
  build_and_release:
    jobs:
      - daml_test:
          <<: *only-release-tags
          daml_sdk_version: "0.13.54"
      - mvn_test:
          <<: *only-release-tags
          daml_sdk_version: "0.13.54"
          context: blackduck
      - github_release:
          context: github-refapp-repo-context
          requires:
            - daml_test
            - mvn_test
          <<: *only-release-tags
